### ISSUE TITLE
Feature Request: RS256

### ISSUE THREAD

**Issue by edenprojectde** [timonson/djwt#10]
I would like to check validity of Google Login JWT's which uses RS256.

Maybe this is already possible and i'm misinterpreting the README? If not, is it something you can/would implement?

**Comment by timonson** [comment]
Hi @edenprojectde , asymmetric signing algorithms like RS256 will be implemented very soon. You should be able to check the validity of Google's JWTs then. Right now only HMAC SHA-256 ("HS256"), HMAC SHA-512 ("HS512") and none (Unsecured JWTs) are implemented. I hope this answers your question.

**Comment by edenprojectde** [comment]
@timonson do you think they have this on their todo already? Can we push this a little by making an issue on the deno repo or maybe there is one? 
Can't find it in the issues of deno as of right now.
Only found this PR: https://github.com/denoland/deno/pull/6046

**Comment by invisal** [comment]
I am working on one crypto library for Deno. Right now you can do verify with it. I still work on sign next if you are interested in using it.

https://github.com/invisal/god_crypto/wiki/RSA#verify-rs256-jwt

**Comment by timonson** [comment]
Thank you for letting me know @invisal ! I will take a closer look over the weekend. Is the goal of your library that it will be adopted into the official Deno repository at one point?

**Comment by invisal** [comment]
The direction is not very clear. Currently, we will try to use WebCrypto if it is available, then fallback to our own implementation. So if you bundle our code and use it in browser, it use WebCrypto. If you use run using deno, then it will use pure Javascript implementation.

At some point, Deno will implement crypto library. It can be either
- Deno will implement WebCrypto. In that case, we will work out of the box since we use WebCrypto
- Deno will implement their own crypto, then, we will use WebCrypto in the browser, use deno crypto implemention, and fallback to our algorithm if user use algorithm that does not support in webcrypto and deno crypto.

At the end of day, we want to be thin layer wrapping around WebCrypto and deno crypto,

Right now, the library is still young and I try to go around the community and see which feature everyone need the most.

**Comment by timonson** [comment]
I just added the RS256 algorithm to the new [rs256 branch](https://github.com/timonson/djwt/tree/rs256). Before I merge this branch to master I would love to get some code reviews for this branch @edenprojectde @alexander-eng @invisal @MariusVatasoiu @esquevin . Please let me know when you looked at the new branch. Thank you!

**Comment by timonson** [comment]
I made a PR here: https://github.com/timonson/djwt/pull/34

Please comment if you find something.

Thanks!

**Comment by austenstone** [comment]
updates? 👀

**Comment by austenstone** [comment]
Appreciate the response @timonson. I got it working after some difficulty with [crypto.subtle.importKey](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/importKey).

See example for [Authenticating as a GitHub App](https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps#authenticating-as-a-github-app):
https://github.com/austenstone/github-pooled-notification-server/blob/main/communication/github.ts#L80-L119
