### ISSUE TITLE
bug: window is not defined

### ISSUE THREAD

**Issue by alexanderGalushka** [timonson/djwt#4]
on jwt token validation encountered:

```
error: Uncaught Error: Uncaught ReferenceError: window is not defined
    at WorkerImpl.#poll ($deno$/web/workers.ts:210:17)
```

**Comment by timonson** [comment]
Hi @alexanderGalushka does this error only appear when using `Deno.bundle()`. I could not replicate this error using the normal `deno run` or `deno test` command. I am a little bit confused because the `window.btoa` etc. functions still exist in the latest `deno` version. Would you be so kind and tell me exactly how to replicate the error?

Additionally I just found out that there is a [base64 module in the deno standard library now](https://github.com/denoland/deno/blob/master/std/encoding/base64.ts). I guess we both agree that it would be better to use this module from now on. If that is the case, let me know if you wanna adapt your PR.

**Comment by alexanderGalushka** [comment]
@timonson yeah, interesting, I run the code in the bundle which is the wrapped into the web worker

**Comment by alexanderGalushka** [comment]
@timonson if you can merge PR #5 for it would be great, it will unblock my work for now and we can looking into using the std base64 module
